### ISSUE TITLE
Non latin characters broken

### ISSUE THREAD

**Issue by ks-zealot** [DavidColson/UnrealInk#13]
How to reproduce:
Create simple project

1. Add stort with non latin (for example cyrillic) story.
2. Display story with any way( UE_LOG macro, widget, etc)
3. Characters are displays as question marks

**Comment by ks-zealot** [comment]
Notice its fixed at last commit

**Comment by dimanjy** [comment]
It's still broken! Cyrillic characters are displayed as questions. I tried both source .ink file is in UTF-8 and Windows-1252 encodings.
